n_epochs: 20
batch_size: 32
learning_rate: 0.0002
weight_decay: 0.0002
model_name: resnet50
weight_name: IMAGENET1K_V1
load_weight: True
freeze_backbone: False
default_data_transform: False
check_points: ./ckpt
ckpt_name: resnet50